.TH tdlisten 1 2014-01-01

.SH NAME
tdlisten \- a command line utility to listen for events from a Telldus TellStick

.SH SYNOPSIS
.B tdlisten [options]

.SH DESCRIPTION
.B tdlisten
is a tool to receive events from devices configured
with a Telldus TellStick. 
.B tdlisten
waits for events from the device selected using the
.B -d
command line option and prints the new device status
to standard output. See 
.B NOTES
for the device status codes. 
For TELLSTICK_DIM events (status code=16), the current value is output after the
new status code, between parentheses.
If no device is selected using the
.B \-d
option, events from all devices are shown.

.SH OPTIONS
.TP 10
.B \-v 
verbose
.TP
.B \-c
continuous (do not exit when event is received)
.TP
.B \-i
id (output device id for every receiver event)
.TP
.B \-d device
select device
.TP
.B \-h
help

.SH EXAMPLES
.nf
$ tdlisten -d "Doorbell"
.fi
.br
Listen for a single event from the device named "Doorbell", print
the new device state, and exit.
.P
.nf
$ tdlisten -c -i
.fi
.br
Listen for events from all devices, do not halt after first event.
Output the device id for each event (format: <id>: <method>).

.SH NOTES
Device state codes:
.TP 18
TELLSTICK_TURNON
1
.TP
TELLSTICK_TURNOFF
2
.TP
TELLSTICK_BELL
4
.TP
TELLSTICK_TOGGLE
8
.TP
TELLSTICK_DIM
16
.TP
TELLSTICK_LEARN
32
.TP
TELLSTICK_EXECUTE
64
.TP
TELLSTICK_UP
128
.TP
TELLSTICK_DOWN
256
.TP
TELLSTICK_STOP
512

.SH SEE ALSO
.BR tdtool (1)

.SH AUTHOR
Jan-Pascal van Best <janpascal@vanbest.org>

